apiVersion: v2
name: pagopa-print-payment-notice-generator
description: Microservice that handles services for notice print generation
type: application
version: 0.56.0
appVersion: 0.4.10-1-PIDM-2413-completing-status-indefinitely
dependencies:
  - name: microservice-chart
    version: 8.4.1
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
