apiVersion: v2
name: pagopa-print-payment-notice-generator
description: Microservice that handles services for notice print generation
type: application
version: 0.54.0
appVersion: 0.4.9-1-PIDM-2384-fix-poste-name
dependencies:
  - name: microservice-chart
    version: 8.4.1
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
