apiVersion: v2
name: pagopa-print-payment-notice-generator
description: Microservice that handles services for notice print generation
type: application
version: 0.60.0
appVersion: 0.4.10-5-PIDM-2477-change-state-fail-on-notice-error
dependencies:
  - name: microservice-chart
    version: 8.4.1
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
